name: garden-app-tests
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: setup
      working-directory: ./frontend
      run: ls -la
    - name: copy .env file
      run: cp /frontend/.env /frontend/.env 
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - name: run flutter tests
      working-directory: ./frontend
      run: flutter pub get && flutter test
