name: garden-app-tests
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: flutter test
